name: 'Settings Tray'
type: module
description: 'Allows users to directly edit the configuration of blocks on the current page.'
package: Core
# version: VERSION
dependencies:
  - drupal:block
  - drupal:toolbar
  - drupal:contextual

# Information added by Drupal.org packaging script on 2025-11-13
version: '11.1.9'
project: 'drupal'
datestamp: 1762992166
